# Generated by Django 3.1.1 on 2020-09-24 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20200924_1210'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='PlaceOrder',
        ),
    ]
