# Generated by Django 3.1.1 on 2020-09-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_auto_20200924_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeorder',
            name='Veg_or_NonVeg',
        ),
        migrations.AddField(
            model_name='placeorder',
            name='Address',
            field=models.CharField(default='For delivery', max_length=1000),
        ),
        migrations.AddField(
            model_name='placeorder',
            name='BEVERAGES',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeorder',
            name='DESSERT',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeorder',
            name='NON_VEG_PIZZA',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeorder',
            name='Phone_Number',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeorder',
            name='SIDES',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeorder',
            name='VEG_PIZZA',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placeorder',
            name='Name',
            field=models.CharField(default='Name', max_length=100),
        ),
    ]
